metadata_db:
  host: 10.0.4.7
  name: pubmed_database_test_yuanshi
  user: wangyuanshi
  port: 5432
  password: "123456"

vector_db:
  db: /data3/guofang/AIgnite-Solutions/PD_TEST_Langtaosha/vector_db/pubmed_database_test_yuanshi/faiss/shards
  gritlm_model: GritLM/GritLM-7B
  gritlm_model_name: GritLM/GritLM-7B
  hf_home: null
